version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
     - ./data/db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: never-say-nosql
      MYSQL_DATABASE: rt-prices
      MYSQL_USER: dev
      MYSQL_PASSWORD: root9191
    ports:
      - 3306:3306